version: "3.8"

services:
    # bookstore:
    #     build:
    #         context: ./bookstore
    #     ports:
    #         - "3000:3000"
    #     environment:
    #         - DATABASE_URL=mysql://root:root_password@db:3306/bookstore
    #     depends_on:
    #         - db

    # user_service:
    #     build:
    #         context: ./user
    #     ports:
    #         - "3002:3002"
    #     environment:
    #         - DATABASE_URL=mysql://root:root_password@db:3306/bookstore
    #     depends_on:
    #         - db

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3306:3306"
